# https://wiki.eclipse.org/Babel_/_Server_Tool_Development_Process#Setting_up_a_Development_Environment
babel:
  image: babel-docker:latest
  volumes:
    - babel_addons:/var/www/babel/addons
    - babel_logs:/var/log/httpd
    - babel_updatesite:/appl
  ports:
    - 80:80
  restart: always
  links:
    - mysql
  command: "httpd -D FOREGROUND"

mysql:
  image: mysql:5.6
  volumes:
   - babel_dbdata:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: babeladmin
    MYSQL_DATABASE: babel
  restart: always
